# Site
repository: lukey1000/Portfolio
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luke Brown
title: Information Security Officer
email: lukeandrewbrown@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyll
github_username: lukey1000
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: luke-brown-0567181b1
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Download my CV
  icon: fas fa-download
  url: https://drive.google.com/file/d/10HosDVIv3K9uG5cof6eixYhuk1AbbS_z/view?usp=sharing
# - title: 
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/Lukey.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Luke and I'm an Infosec nerd, currently employed as an Information Security Officer with a federal government department. You can download my CV with the button above.
  I've had an incredibly rewarding career that boils down to making problems go away, some highlights include:
  - Setting up a temporary office for the Australian Prime Minister inside a castle in the UK during COVID. Seriously, those castle designers could have included some ethernet ports in the walls.
  - The privilege of attending ANZAC Day ceremonies at Amiens in France in 2018.
  - Collaborating with ASD as the blue half of an extensive purple team operation. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Infosec Goodies
        link: github.com/lukey1000/Infosec-Goodies
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #
        description: | # this will include new lines to allow paragraphs
          A collection of useful queries and tools that I have written or adapted for my own usage including:
          - KQL Queries for Defender
          - ArcSight Logger Queries
          - Powershell Scripts
          - Bash and Python Scripts
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNSW Canberra @ ADFA
        caption: 2023 - 2025
        sub_title: Master of Cyber Security (Digital Forensics)
        description: | # this will include new lines to allow paragraphs
          I'm greatly enjoying the deep thought on cybersecurity required to excel in this program.
          Highlights so far include:
          - A semester spent researching BYOD vulnerabilities and developing a proof of concept for a website cloning credential stealer.
          - Developing a futuristic Scrum model that replaced the Scrum Master with an AI.
   
  - title: Development Goals # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Industry Certifications
        caption: Studying for certifications keeps me focused
        link: https://www.giac.org/certified-professional/Luke-Brown/199859
        link_text: My GIAC Professional Page
        description: | # this will include new lines to allow paragraphs
          GIAC AB | GSEC | GCED | GCIH | GX-IH | AZ-104 | AZ-500 | SC-200 | ITIL v3 | Mental Health First Aid |
        
          I'm proudest of being GIAC Experienced Incident Handler #346. Below are my next development goals.
          - CISSP. Exam in December 2023.
          - CISA. This + CISSP would make me eligible for IRAP. Early - mid 2024.
          - GIAC Security Expert. Several years down the track, to get there I need: GX-CS, GCFE, GCFA, GX-FA, GCIA, GX-IA.
          - Azure Security Architect Expert. Early 2024.
          - OSCP. Late 2024.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag