# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luke Brown
title: Information Security Specialist
email: lukeandrewbrown@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username: lukey1000
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
#instagram_username: 
linkedin_username: luke-brown-0567181b1
# xing_username: 
# pinterest_username: 
#youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/gxih.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Luke, and I'm an Infosec nerd.
  I have nearly two decades of diverse IT experiences, and I've worked everywhere from Micronesia to Manhattan.
  I've solved IT issues for the Prime Minister while mid-flight on RAAF Aircraft and collaborated with ASD on purple team cyber operations.
  This project is for me to get more familiar with git, webdev, and ruby.

content:
- title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNSW Canberra @ ADFA
        caption: 2023 - 2025
        sub_title: Master of Cyber Security (Digital Forensics)
        quote: >
          The Master of Cyber Security (Digital Forensics) at UNSW Canberra provides students with the knowledge, understanding and skills to enable the recovery of admissible evidence from digital media. Students will understand the ethical and legal issues associated with cybercrime investigations and develop decision-making tools to assess, evaluate and analyse digital data.
        description: | # this will include new lines to allow paragraphs
          I'm greatly enjoying the research and deep thought on cyber topics that is encouraged in this degree.

          I'm proud of the research I have undertaken on BYOD related vulnerabilities.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Brazilian Jiu Jitsu
      - Powerlifting
      - Cooking
      - Yoga
      - Skiing
      - Learning Japanese

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
