# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luke Brown
title: Information Security Officer
email: lukeandrewbrown@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: lukey1000
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: luke-brown-0567181b1
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Luke and I'm an Infosec nerd.
  I have nearly two decades of diverse IT experiences in more than 50 countries that range from solving mid-flight IT issues for the Prime Minister on his RAAF Aircraft to collaborating with ASD on purple team operations.

content:
  - title: Certifications # Title for the section
    content:
     - layout: top-middle
       title: GIAC Experienced Incident Handler
       link: https://www.credly.com/badges/f19d9113-0125-47c0-bacd-1016e7e5d181/public_url
       gxih_image: images/gxih.png
       quote: >
         The GIAC Experienced Incident Handler Certification (GX-IH) demonstrates a candidates superior incident response skills.
       
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Federal Government
        link: .gov.au
        # link_text: boringcompany.com
        sub_title: Information Security Officer
        caption: October 2022 - Present
        quote: >
          Ensuring that the departments people, processes, and technology are defensible.
        description: | # this will include new lines to allow paragraphs
            - Designed and led the security assessment activities required as part of the Authority to Operate process for a large scale complex Azure Hybrid Cloud deployment. 
            - Led threat detection engineering activities during a significant purple team assessment operation in collaboration with ASDs Cyber Maturity team. 
            - Designed a honeypot strategy to detect stealthy bloodhound scans, Kerberoasting and DCSync Attacks, and website cloning attacks. 
      - layout: left
        title: Department of Prime Minister and Cabinet
        link: pmc.gov.au
        # link_text: boringcompany.com
        sub_title: VIP IT Support Advisor to the Prime Minister's Office
        caption: September 2013 - October 2022
        quote: >
          From Micronesia to Manhattan, I travelled the world with the Prime Minister's Office.
        description: | # this will include new lines to allow paragraphs
            - On more than 50 international visits I had sole responsibility for ensuring that any and all technical and communications problems were no longer problems. 
            - Took direct calls from the Prime Minister at any time of day or night and provided immediate solutions to requests spanning Level 1 helpdesk to network and systems administration tasks. 
            - Designed and implemented portable packet capture and intruder detection system capabilities based on Security Onion and PFSense that significantly enhanced the security posture of temporary overseas office setups.  
      - layout: left
        title: Older Stuff
        link: archive.org
        # link_text: boringcompany.com
        sub_title: Service Desk Analyst > Desktop Support > System Administrator
        caption: November 2007 - September 2013
        quote: >
          Worked my way from Service Desk to Sysadmin across multiple companies at the start of my career.
        description: | # this will include new lines to allow paragraphs
            - Upgraded the Canberra Hospital from Windows 2000 to XP.
            - System Administrator for Lockheed Martin Australia at the ATO. 
            - Became a superstar at talking nontechnical staff through phone based troubleshooting.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNSW Canberra @ ADFA
        caption: 2023 - 2025
        sub_title: Master of Cyber Security (Digital Forensics)
        quote: >
          The Master of Cyber Security (Digital Forensics) at UNSW Canberra provides students with the knowledge, understanding and skills to enable the recovery of admissible evidence from digital media. Students will understand the ethical and legal issues associated with cybercrime investigations and develop decision-making tools to assess, evaluate and analyse digital data.
        description: | # this will include new lines to allow paragraphs
          I'm greatly enjoying the research and deep thought on cyber topics that is encouraged in this degree.

          I'm proud of the research I have undertaken on BYOD related vulnerabilities.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Brazilian Jiu Jitsu
      - Powerlifting
      - Cooking
      - Yoga
      - Skiing
      - Learning Japanese

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
